const officeQuotes = [
    { id: 0, author: "Michael Scott", quote: "Would I rather be feared or loved? Easy. Both. I want people to be afraid of how much they love me." },
    { id: 1, author: "Jim Halpert", quote: "Right now, this is just a job. If I had to advance any higher in this company, this would be my career. And uh, if this were my career, I'd have to throw myself in front of a train." },
    { id: 2, author: "Dwight Schrute", quote: "IDENTITY THEFT IS NOT A JOKE, JIM! MILLIONS OF FAMILIES SUFFER EVERY YEAR." },
    { id: 3, author: "Pam Beesly", quote: "And I feel god in this Chili's tonight." },
    { id: 4, author: "Michael Scott", quote: "I'm not superstitious, but am a little stitious." },
    { id: 5, author: "Michael Scott", quote: "I'm an early bird and I'm a night owl. So I'm wise and I have worms." },
    { id: 6, author: "Jim Halpert", quote: "wE didn't play many video games in Scranton. Instead, we'd do stuff like... uh, Pam and I would sometimes hum the same high-pitched note and try to get Dwight to make an appointment with an ear doctor. And, uh, Pam called it... Pretendinitis." },
    { id: 7, author: "Kelly Kapoor", quote: "ACK. THEY’RE TOTALLY DIFFERENT. TRASH TALK IS HYPOTHETICAL LIKE YOUR MOM IS SO FAT SHE CAN EAT THE INTERNET. BUT SMACK TALK IS HAPPENING LIKE RIGHT NOW. LIKE: YOU’RE UGLY, AND I KNOW IT FOR A FACT ’CAUSE I GOT THE EVIDENCE RIGHT THERE." },
    { id: 46, author: "Jim Halpert", quote: "It is not a good time for me to lose my job since I have some pretty big long-term plans in my personal life with Pam that I’d like her parents to be psyched about. So, I am about to do something very bold in this job that I’ve never done before: try." },
    { id: 47, author: "Pam Beesly", quote: "I’m guessing Angela is the one in the neighborhood that gives the trick-or-treaters toothbrushes, pennies, walnuts." },
    { id: 48, author: "Kevin Malone", quote: "The people here are amazing debaters. I guess you can say they are master-baters." },
    { id: 49, author: "Michael Scott", quote: "I say dance, they say, ‘How high?'" },
    { id: 50, author: "Dwight Schrute", quote: "Jim told me you could buy gaydar online." },
    { id: 51, author: "Michael Scott", quote: "Dwight you ignorant sl*t." },
    { id: 52, author: "Stanley Hudson", quote: "I wake up every morning in a bed that’s too small, drive my daughter to a school that’s too expensive, and then I go to work to a job for which I get paid too little. But on pretzel day? Well, I like pretzel day." },
    { id: 53, author: "Michael Scott", quote: "Why are you the way that you are? Honestly, every time I try to do something fun, or exciting, you make it… not that way. I hate… so much about the things that you choose to be." },
    { id: 54, author: "Jim Halpert", quote: "I think it’s great that the company’s making a commercial, because not very many people have heard of us. I mean, when I tell people I work at Dunder Mifflin, they think that we sell mufflers or muffins or mittens or… and frankly, all of those sound better than paper, so I let it slide." },
];

const newGirlQuotes = [
    { id: 8, author: "Nick", quote: "I’m pretty sure I’m having a heart attack and I haven’t arranged for anyone to clear my internet history. I wasn’t building a bomb, I was just curious." },
    { id: 9, author: "Nick", quote: "I am not a successful adult. I don’t eat vegetables and/or take care of myself." },
    { id: 10, author: "Nick", quote: "I don’t dance! I’m from that town in 'Footloose.'" },
    { id: 11, author: "Nick", quote: "Do I regret it? Yes. Would I do it again? Probably." },
    { id: 12, author: "Nick", quote: "I can’t go to jail! I’m too sarcastic for the white gangs!" },
    { id: 13, author: "Nick", quote: "Any time a man wants to show a woman how to do something from behind, it’s just because he wants an excuse to get real close and breathe on her neck. Watch any sports movie." },
    { id: 14, author: "Jess", quote: "So when I do the chicken dance, I do it a little differently. Instead of doing claps, I like to do a peck. It’s more realistic." },
    { id: 15, author: "Jess", quote: "Everything you say sounds really creepy when you’re not wearing pants." },
    { id: 16, author: "Jess", quote: "I thought we talked about you not wearing your shower diaper in the kitchen." },
    { id: 17, author: "Schmidt", quote: "Well, Nick, I’m out of tears. Plumb out. Now, all that’s left is just yellowish goo. That’s right, Nick, goo." },
    { id: 18, author: "Schmidt", quote: "If pot were a piano, Nick would be a nine-year-old Chinese girl." },
    { id: 19, author: "Jess", quote: "I’m only attracted to guys who are afraid of success and think someone famous stole their idea." },
    { id: 128, author: "Jess", quote: "I might as well call you Bridge to Terabithia because you make children cry." },
    { id: 129, author: "Jess", quote: "You’re making a huge, life-ruining mistake by moving in with a woman who turned you into an agoraphobic, turtle-faced, borderline alcoholic." },
    { id: 130, author: "Jess", quote: "I thought we talked about you not wearing your shower diaper in the kitchen." },
    { id: 131, author: "Nick", quote: "Look, we’re not trying to be mean. We just don’t want you to be yourself… in any way." },
    { id: 132, author: "Nick", quote: "I have decided to give up on women and put all of that energy into tomatoes." },
    { id: 133, author: "Nick", quote: "Lying makes me sweat. That’s why I can’t play poker or talk to pregnant women." },
    { id: 134, author: "Nick", quote: "Look at that font! What is this? Amateur hour? At least use Palatino." },
    { id: 135, author: "Schmidt", quote: "Beans are nothing but soggy nuts." },
    { id: 136, author: "Schmidt", quote: "You were denied a cell phone because you have the credit score of a homeless ghost." },
    { id: 137, author: "Schmidt", quote: "Get rid of it, Jess. Pine has no place in this loft. It’s the wood of poor people and outhouses." },
    { id: 138, author: "Winston", quote: "If I were off my rocker, would I take a weekly selfie with my cat?" },
    { id: 139, author: "Winston", quote: "I’m pretty sure they call her ‘The Fish’ because she’s tough but fair, like a lot of fish I’ve met." },
];

const parksAndRecQuotes = [
    { id: 20, author: "April", quote: "I wanted to make fun of stupid people while I get drunk. My two true passions." },
    { id: 21, author: "Andy", quote: "When they say 2% milk, I don't know what the other 98% is." },
    { id: 22, author: "Andy", quote: "Call an ambulance! A different ambulance! The one I ran into!" },
    { id: 23, author: "Ron", quote: "I like saying no. It lowers their enthusiasm." },
    { id: 24, author: "Ron", quote: "There's only one thing I hate more than lying: skim milk. Which is water that's lying about being milk." },
    { id: 25, author: "Ron", quote: "Strippers do nothing for me…but I will take a free breakfast buffet anytime, anyplace." },
    { id: 26, author: "Andy", quote: "I tried to make ramen in the coffee pot and I broke everything." },
    { id: 78, author: "Andy", quote: "Just remember, every time you look up at the moon, I, too, will be looking at a moon. Not the same moon, obviously. That's impossible." },
    { id: 79, author: "Andy", quote: "I’m fine. It’s just that life is pointless and nothing matters and I’m always tired." },
    { id: 80, author: "Chris", quote: "If I keep my body moving, and my mind occupied at all times, I will avoid falling into a bottomless pit of despair." },
    { id: 81, author: "Ron", quote: "Put some alcohol in your mouth to block the words from coming out." },
    { id: 82, author: "Ron", quote: "I regret nothing. The end." },
    { id: 83, author: "Andy", quote: "I have no idea what I’m doing, but I know I’m doing it really, really well." },
    { id: 84, author: "Leslie", quote: "I would like a glass of red wine and I’ll take the cheapest one you have because I can’t tell the difference." },
    { id: 85, author: "Ben", quote: "No, that’s Buckingham Palace. Hogwarts is fictional. You do know that, don’t you? It’s important to me that you know that" },
    { id: 86, author: "Leslie", quote: "You know my code. Hoes before bros. Uteruses before duderuses. Ovaries before brovaries." },
    { id: 87, author: "Andy", quote: "Leslie, I typed your symptoms into the thing up here, and it says you could have network connectivity problems." },
    { id: 88, author: "Ron", quote: "I’d wish you the best of luck, but I believe luck is a concept created by the weak to explain their failures." },
    { id: 89, author: "Andy", quote: "I’m allergic to sushi. Every time I eat more than 80 pieces, I throw up." },
    { id: 90, author: "Ron", quote: "Child labor laws are ruining this country." },
    { id: 90, author: "Ron", quote: "On my deathbed, my final wish is to have my ex- wives rush to my side so I can use my dying breath to tell them both to go to hell one last time." },
    { id: 91, author: "Ron", quote: "Normally, if given the choice between doing something and nothing, I’d choose to do nothing. But I will do something if it helps someone else do nothing. I’d work all night, if it meant nothing got done." },
    { id: 92, author: "Ron", quote: "Any dog under 50 pounds is a cat and cats are useless." },
    { id: 93, author: "Ron", quote: "So, you talked to Tammy? What’s it like to stare into the eye of Satan’s butthole?" },
    { id: 94, author: "Ron", quote: "I once worked with a guy for three years and never learned his name. Best friend I ever had. We still never talk sometimes." },
];

const devQuotes = [
    { id: 27, author: "Jacob", quote: "If you polish a turd all you still have a turd." },
    { id: 28, author: "Jacob", quote: "The best time to cut a tree was yesterday." },
    { id: 29, author: "Jacob", quote: "The definition of insanity is to do the same thing, but expect different results, so I must be crazy for coding." },
    { id: 30, author: "Jacob", quote: "I only cry in the shower, for recycling purposes." },
    { id: 55, author: "Jacob", quote: "I don't do smoke cigarettes or drink alcohol, but I do have an unhealthy obsession with cookie dough ice-cream." }
];

const adventureTimeQuotes = [
    { id: 31, author: "Jake", quote: "Dude, suckin’ at something is the first step to being sorta good at something." },
    { id: 32, author: "Jake", quote: "To live life, you need problems. If you get what you want the minute you want it, then what's the point of living?" },
    { id: 33, author: "Ice King", quote: "I've soiled my tunic, completely by choice!" },
    { id: 34, author: "Ice King", quote: "I'm toying with you... psychologically!" },
    { id: 35, author: "Lemongrab", quote: "It has cost me much, but I have learned lemon need not squeeze lemon to survive!" },
    { id: 64, author: "Jake", quote: "You're getting hung up on imaginary problems. You gotta focus on what's real." },
    { id: 65, author: "Finn", quote: "I say creepy is just another label we used to distance ourselves from stuff we don't understand, or that it reminds us of something in ourselves that we're not comfortable with." },
    { id: 66, author: "Lumpy Space Princess", quote: "I'm really sorry Finn. I can't help you because my parents are horrible idiots." },
    { id: 67, author: "Duke of Nuts", quote: "People make mistakees. It's all a part of growing up, an you never really stop growing." },
    { id: 68, author: "Ice King", quote: "Sometimes, you don't cry because you're afraid of real emotion." },
    { id: 69, author: "Demon Cat", quote: "I have approximate knowledge of many things." },
    { id: 70, author: "Finn", quote: "Everything small is just a smaller version of something big." },
    { id: 71, author: "BMO", quote: "When bad things happen, I know you want to believe they are a joke, but sometimes life is scary and dark. That is why we must find the light." },
    { id: 72, author: "Finn", quote: "Let’s always be stupid, forever!" },
    { id: 73, author: "Finn", quote: "Don’t you call sweatpants: “give up on life pants” Jake?" },
    { id: 74, author: "Princess Bubblegum", quote: "People get built different. We don’t need to figure it out, we just need to respect it." },
    { id: 75, author: "Ice King", quote: "We will do nothing but kiss and eat a whole bunch till we get fat and die." },
    { id: 76, author: "Jake", quote: "Bad biscuits make the baker broke, bro." },
    { id: 77, author: "Ice King", quote: "I’m collecting them all first to be sure I make the right choice!" },

];

const spongebobQuotes = [
    { id: 36, author: "Spongebob", quote: "Hey Patrick, I thought of something funnier than 24… 25!" },
    { id: 37, author: "Plankton", quote: "Goodbye everyone, I’ll remember you all in therapy." },
    { id: 38, author: "Mr. Krabs", quote: "A 5 letter word for happiness –MONEY." },
    { id: 38, author: "Patrick", quote: "If I was a mom… this would be kind of shocking. Just call me daddy!" },
    { id: 39, author: "Patrick", quote: "Is mayonnaise an instrument?" },
    { id: 40, author: "Plankton", quote: "I don’t get it. No matter what I do, I always end up being squashed by someone bigger than me." },
    { id: 41, author: "Mr. Krabs", quote: "The boy cries you a sweater of tears and you kill 'em." },
    { id: 42, author: "Squidward", quote: "I order the food, you cook the food. The customer gets the food. We do that for 40 years, and then we die." },
    { id: 43, author: "Spongebob", quote: "I know of a place where you never get harmed. A magical place with magical charm. Indoors, indoors, indoors!" },
    { id: 44, author: "Patrick", quote: "Once upon a time there was an ugly barnacle. He was so ugly that everyone died. The end!" },
    { id: 45, author: "Patrick", quote: "Dumb people are always blissfully unaware of how dumb they really are…" },
    { id: 114, author: "Spongebob", quote: "He's a ghost in denial he needs us now more than ever." },
    { id: 115, author: "Patrick", quote: "Firmly grasp it!" },
    { id: 116, author: "Spongebob/Patrick", quote: "(Spongebob) Go. Run away like all the others. No one would want a friend as ugly as I am. (Patrick) Sure they would! It makes them feel better about the way that they look!" },
    { id: 117, author: "Patrick", quote: "Is this the Krusty Krab? No. This is Patrick!" },
    { id: 118, author: "Mr. Krabs", quote: "Did you smell it? That smell. A kind of smelly smell. The smelly smell that smells...smelly." },
    { id: 119, author: "Plankton", quote: "F is for fire that burns down the whole town. U is uranium…bombs! N is for no survivors!" },
    { id: 120, author: "Spongebob", quote: "You never really know the true value of a moment, until it becomes a memory." },
    { id: 121, author: "Squidward", quote: "You can’t fool me. I listen to public radio!" },
    { id: 122, author: "Spongebob", quote: "If I were to die right now in a fiery explosion due to the carelessness of a friend… Then it would just be alright." },
    { id: 123, author: "Spongebob", quote: "Always follow your heart – unless your heart is bad with directions." },
    { id: 124, author: "Mr. Krabs", quote: "It’s not always what you say that matters, sometimes it’s what you don’t say." },
    { id: 125, author: "Patrick", quote: "You got it set to ‘M’ for mini when it should be set to ‘W’ for wumbo." },
    { id: 126, author: "Plankton", quote: "Oh Karen, my computer wife, if only I could have managed to steal the secret to Krabs’ success. The formula for the Krabby Patty…Ohhh…Then people would line up to eat at MY restaurant! Lord knows I’ve tried. I’ve exhausted every evil plan in my filing cabinet…from A to Y!" },
    { id: 127, author: "Plankton", quote: "Goodbye everyone, I'll remember you all in therapy." },
];

const friendsQuotes = [
    { id: 56, author: "Chandler", quote: "I can handle this. Handle is my middle name. Actually, handle is the middle of my first name." },
    { id: 57, author: "Chandler", quote: "All right, look if you absolutely have to tell her the truth, at least wait until the timing’s right. And that’s what deathbeds are for." },
    { id: 58, author: "Ross", quote: "If you’re going to call me names, I would prefer Ross, the Divorce Force. It’s just cooler." },
    { id: 59, author: "Joey", quote: "It’s a moo point. It’s like a cow’s opinion; it doesn’t matter. It’s moo." },
    { id: 60, author: "Chandler", quote: "I’m not so good with the advice. Can I interest you in a sarcastic comment?" },
    { id: 61, author: "Phoebe", quote: "Come on Ross you’re a palaeontologist – dig a little deeper." },
    { id: 62, author: "Joey", quote: "How you doin'?" },
    { id: 63, author: "Janice", quote: "I'm a young woman, I have needs." },
    { id: 95, author: "Chandler", quote: "I'm hopeless and awkward and desperate for love." },
    { id: 96, author: "Chandler", quote: "Cheese. It’s milk that you chew." },
    { id: 97, author: "Chandler", quote: "Until I was 25, I thought the response to 'I love you' was 'Oh, crap.'" },
    { id: 98, author: "Chandler", quote: "I say more dumb things before 9 A.M. than most people say all day." },
    { id: 99, author: "Chandler", quote: "I'm a gym member. I try to go four times a week, but I've missed the last twelve hundred times." },
    { id: 100, author: "Chandler", quote: "When I first meet somebody it’s usually panic, anxiety, and a great deal of sweating." },
    { id: 101, author: "Chandler", quote: "Oh, I know. This must be so hard. ‘Oh, no! Two women love me. They’re both gorgeous and sexy. My wallet’s too small for my fifties, and my diamond shoes are too tight!'" },
    { id: 102, author: "Chandler", quote: "Oh, man. In my next life, I’m coming back as a toilet brush!" },
    { id: 103, author: "Chandler", quote: "What must it be like not to be crippled by fear and self-loathing?" },
    { id: 104, author: "Phoebe", quote: "Oh you like that? You should hear my phone number." },
    { id: 105, author: "Phoebe", quote: "Well, if she isn’t (dead), cremating her was a big mistake." },
    { id: 106, author: "Phoebe", quote: "It's so exhausting, waiting for death." },
    { id: 107, author: "Phoebe", quote: "Everybody looks so happy. I hate that." },
    { id: 108, author: "Phoebe", quote: "I wish I could, but I don't want to." },
    { id: 109, author: "Phoebe", quote: "I’m a lady, Monica. I don’t kiss and tell. But this hickey speaks for itself." },
    { id: 110, author: "Rachael", quote: "We are dessert stealers. We are living outside the law." },
    { id: 111, author: "Rachael", quote: "No uterus, no opinion." },
    { id: 112, author: "Rachael", quote: "Oh I'm sorry, did my back hurt your knife?" },
    { id: 113, author: "Rachael", quote: "Isn’t this exciting! I earned this! I wiped tables for it, I steamed milk for it, and it was totally… not worth it. Who’s FICA? Why’s he getting all my money?" },
];

export { officeQuotes, newGirlQuotes, parksAndRecQuotes, devQuotes, adventureTimeQuotes, spongebobQuotes, friendsQuotes };
